### ISSUE TITLE
Panic for batch sizes > 254 in Node

### ISSUE THREAD

**Issue by michielbdejong** [tigerbeetle/tigerbeetle#2348]
Hi! I was expecting to be able to do batch sizes up to 8190 from JavaScript, but in practice any batch size of 255 or higher consistently leads to a panic: `reached unreachable code`. What am I doing wrong here?
```js
import { CreateAccountError, createClient, CreateTransferError, id } from 'tigerbeetle-node';

const client = createClient({
  cluster_id: 0n,
  replica_addresses: ["3000"],
});

async function runBatch(numTrans) {
  const transferBatch = [];
  for (let i = 0; i < numTrans; i++) {
    transferBatch.push({
      id: id(),
      debit_account_id: 1n,
      credit_account_id: 2n,
      amount: 5n,
      pending_id: 0n,
      user_data_128: 0n,
      user_data_64: 0n,
      user_data_32: 0,
      timeout: 0,
      ledger: 1,
      code: 720,
      flags: 0,
      timestamp: 0n,
    });
  }
  console.log(`Batch of size ${numTrans} start ...`);
  await client.createTransfers(transferBatch).then((transferErrors) => {
    if (transferErrors.length > 0) {
      transferErrors.map(error => {
        console.log(transferBatch[error.index], CreateTransferError[error.result]);
        return {
          index: error.index,
          result: CreateTransferError[error.result]
        }
      });
      process.exit(1);
    }
  });
  console.log(`Batch of size ${numTrans} done.`);
}

async function createAccounts() {
  await client.createAccounts([{
    id: 1n,
    debits_pending: 0n,
    debits_posted: 0n,
    credits_pending: 0n,
    credits_posted: 0n,
    user_data_128: 0n,
    user_data_64: 0n,
    user_data_32: 0,
    reserved: 0,
    ledger: 1,
    code: 1,
    flags: 0,
    timestamp: 0n,
  }, {
    id: 2n,
    debits_pending: 0n,
    debits_posted: 0n,
    credits_pending: 0n,
    credits_posted: 0n,
    user_data_128: 0n,
    user_data_64: 0n,
    user_data_32: 0,
    reserved: 0,
    ledger: 1,
    code: 1,
    flags: 0,
    timestamp: 0n,
  }]);
  console.log('accounts created');
}

async function run() {
  await createAccounts();
  await runBatch(254);
  await runBatch(255);
}

// ...
run();
```

```sh
$ node ./test.js 
accounts created
Batch of size 254 start ...
Batch of size 254 done.
Batch of size 255 start ...
thread 225666 panic: reached unreachable code
???:?:?: 0x1067e40bb in _node.on_completion (???)
???:?:?: 0x1067edf58 in _clients.c.tb_client.context.ContextType(vsr.client.Client(state_machine.StateMachineType(storage.Storage(io.darwin.IO),.{ .release = .{ ... }, .message_body_size_max = 1048320, .lsm_compaction_ops = 32, .vsr_operations_reserved = 128 }),message_bus.MessageBusType(.client))).on_signal (???)
???:?:?: 0x106815209 in _io.darwin.IO.submit__anon_12328__struct_12749.onComplete (???)
???:?:?: 0x1067ece49 in _io.darwin.IO.flush (???)
Unwind error at address `client.node:0x1067ece49` (error.InvalidUnwindInfo), trace may be incomplete

Abort trap: 6
```

**Comment by michielbdejong** [comment]
I'm seeing the same limit for `createAccounts` btw

**Comment by sentientwaffle** [comment]
Did you start your replica with the `--development` flag? `--development` reduces the batch size (in order to reduce the RAM overhead of the replica).

**Comment by michielbdejong** [comment]
Thanks, indeed this only happens if I run the replica with `--development`. Without that, I do get the expected max batch size of 8190, plus a useful error message, and panic is avoided:
```
$ node test.js 
creating two accounts first ...
accounts created
Batch of size 8190 start ...
Batch of size 8190 done.
Batch of size 8191 start ...
/Users/michiel/gh/ledgerloops/jerboa/node_modules/tigerbeetle-node/dist/index.js:67
                binding.submit(context, operation, batch, (error, result) => {
                        ^

Error: Batch is larger than the maximum message size.
    at /Users/michiel/gh/ledgerloops/jerboa/node_modules/tigerbeetle-node/dist/index.js:67:25
    at new Promise (<anonymous>)
    at request (/Users/michiel/gh/ledgerloops/jerboa/node_modules/tigerbeetle-node/dist/index.js:63:16)
    at Object.createTransfers (/Users/michiel/gh/ledgerloops/jerboa/node_modules/tigerbeetle-node/dist/index.js:86:41)
    at runBatch (file:///Users/michiel/gh/ledgerloops/jerboa/test.js:28:16)
    at run (file:///Users/michiel/gh/ledgerloops/jerboa/test.js:80:9)

Node.js v20.9.0
```

**Comment by sentientwaffle** [comment]
Perfect! Yeah, the lack of a proper error message when exceeding a batch size limit which is <8190 is a known bug. The client is technically aware of it, that info just isn't propagated yet.

If you're doing benchmarking/analysis I would recommend not using `--development`.
